version: "2"
services:
  db:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
    - "27019:27017"
    networks:
      - app-tier
    volumes:
      - ${TRACKSIMULATORPATH}/db:/data/db

  app:
    build: .
    volumes:
    - ./src:/app
    - ${TRACKSIMULATOREXPORT}:/data
    - ${TRACKSIMULATORPATH}/analysis:/analysis
    depends_on:
      - db
    networks:
      - app-tier
    expose:
      - "27017"

networks:
  app-tier:
    driver: bridge